---
# tasks file for minions
- name: Reset Kubernetes
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Join Kubernetes Cluster
  shell: "{{ hostvars[groups['master'][0]]['join_command'].stdout }}"
  when: kubeadm_reset is succeeded
  register: kubeadm_join

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke